apiVersion: v1
kind: Service
metadata:
  name: busybox-svc
  labels:
    app: busybox
spec:
  selector:
    app: busybox
  ports:
    - name: http
      port: 80
      # port: 443
      targetPort: 80
      protocol: TCP
  type: ClusterIP
